import os

from dotenv import load_dotenv


load_dotenv()

EVOLUTION_API_URL= os.getenv('EVOLUTION_API_URL')
EVOLUTION_INSTANCE_NAME= os.getenv('EVOLUTION_INSTANCE_NAME')
EVOLUTION_AUTHENTICATION_API_KEY= os.getenv('AUTHENTICATION_API_KEY')

GROQ_API_KEY = os.getenv('GROQ_API_KEY')

GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID")
GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH")