FROM python:3.13-alpine

WORKDIR /app

# Instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o projeto
COPY . .

# Expõe a porta padrão do Streamlit
EXPOSE 8501

# Comando para iniciar o painel
CMD ["streamlit", "run", "streamlit_dashboard/dashboard.py", "--server.address=0.0.0.0"]
