version: "3.9"

services:
  waha:
    container_name: waha
    image: devlikeapro/waha:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_START_SESSION=default
      - WHATSAPP_RESTART_ALL_SESSIONS=true
      #- WAHA_WEBJS_CACHE_TYPE=local <- tava bugando
    volumes:
      - ./waha_sessions:/app/.sessions
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 6379 --appendonly yes
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  bot:
    build: .
    container_name: bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - waha
      - redis
    restart: always

volumes:
  postgres_data:
  redis:
